# Generated by Django 2.2.6 on 2019-10-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='purchase',
        ),
    ]
