# Generated by Django 2.2.6 on 2019-10-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('medicine', models.CharField(max_length=120)),
                ('clearance_status', models.CharField(max_length=20)),
            ],
        ),
    ]
