# Generated by Django 2.2.6 on 2019-10-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_purchase_clearance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
